version: "3"

services:
    app:
        image: "anomalies-deviations-ui:latest"
        container_name: "anomalies-deviations-ui"
        tty: true
        command: npm start
        ports:
            - "4200:4200"
        volumes:
            - .:/usr/app
            - /usr/app/node_modules
        logging:
            driver: local
            options:
                max-size: "50k"
                max-file: "3"
